# Default system-wide configuration for LangGraph

# Core settings
core:
  debug: false
  log_level: INFO
  max_workers: 4
  timeout: 300  # seconds

# Model settings
models:
  llm:
    default_provider: local-gguf
    providers:
      local-gguf:
        model: mistral-7b-v0.1.Q4_K_M.gguf
        temperature: 0.7
        max_tokens: 512
        top_p: 0.95
        top_k: 40
        context_window: 4096
        n_gpu_layers: -1
        n_threads: 4
        n_batch: 512
      openai:
        model: gpt-3.5-turbo
        temperature: 0.7
        max_tokens: 2000
      anthropic:
        model: claude-2
        temperature: 0.8
        max_tokens: 2000
      huggingface:
        model: gpt2
        temperature: 0.7
        max_tokens: 1000
  embeddings:
    providers:
      openai:
        model: text-embedding-ada-002
      huggingface:
        model: all-MiniLM-L6-v2
      sentence_transformers:
        model: all-MiniLM-L6-v2

# Storage settings
storage:
  vector_store:
    providers:
      pinecone:
        dimension: 1536
        metric: cosine
      weaviate:
        dimension: 1536
        metric: cosine
      milvus:
        dimension: 1536
        metric: cosine
  cache:
    providers:
      redis:
        max_connections: 10
        socket_timeout: 5
      memcached:
        max_connections: 10
        socket_timeout: 5
      memory:
        max_size: 1000

# Workflow settings
workflow:
  max_retries: 3
  timeout: 300
  batch_size: 100
  parallel_execution: true

# Logging settings
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true
  max_size: 10485760  # 10MB
  backup_count: 5

# Monitoring settings
monitoring:
  enabled: true
  metrics_port: 9090
  tracing:
    enabled: true
    provider: jaeger

# Security settings
security:
  enable_auth: false
  jwt_expiry: 3600  # 1 hour
  rate_limit: 100
  rate_limit_period: 3600  # 1 hour

# Document processing settings
document_processing:
  max_document_size: 10485760  # 10MB
  supported_formats:
    - txt
    - pdf
    - docx
    - md
  chunk_size: 1000
  chunk_overlap: 200

# Graph settings
graph:
  max_nodes: 10000
  max_edges: 50000
  update_interval: 300  # 5 minutes

# Memory settings
memory:
  types:
    - short_term
    - mid_term
    - long_term
  max_items: 1000
  cleanup_interval: 3600  # 1 hour
